In [31]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print()

1.13.1+cu117



In [32]:
!nvidia-smi

Mon Feb 20 20:19:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:19:00.0 Off |                  N/A |
| 23%   28C    P8    10W / 250W |      2MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 29%   

In [33]:
# this ensures that the current MacOS version is at least 12.3+
print(torch.backends.mps.is_available())
# this ensures that the current current PyTorch installation was built with MPS activated.
print(torch.backends.mps.is_built())
#If both commands return True, then PyTorch has access to the GPU!

False
False


## Introduction to Tensors
Tensors are a generalization of vectors and matrices to potentially higher dimensions.

Pytorch Tensors are created using `torch.Tensor()`
1. Create Tensors

In [34]:
# scalar 
scalar = torch.scalar_tensor(7)
scalar = torch.tensor(7)
scalar

tensor(7)

In [35]:
print(f'dim : {scalar.ndim}')
print(f'size : {scalar.size()}')
print(f'type : {scalar.type()}')
print(f'total number of eles in input tensor : {scalar.numel()}')
print(f'Stride is the jump necessary to go from one element to the next one in the specified dimension dim : {scalar.stride()}')

dim : 0
size : torch.Size([])
type : torch.LongTensor
total number of eles in input tensor : 1
Stride is the jump necessary to go from one element to the next one in the specified dimension dim : ()


In [36]:
scalar.storage()

 7
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 1]

In [37]:
print(scalar.element_size())


8


In [38]:
scalar.shape

torch.Size([])

In [39]:
#vector
vector = torch.Tensor([3,4])
vector

tensor([3., 4.])

In [40]:
vector.ndim

1

In [41]:
vector.shape

torch.Size([2])

In [42]:
print(f'dim : {vector.ndim}')
print(f'size : {vector.size()}')
print(f'type : {vector.type()}')
print(f'total number of eles in input tensor : {vector.numel()}')
print(f'Stride is the jump necessary to go from one element to the next one in the specified dimension dim : {vector.stride()}')

dim : 1
size : torch.Size([2])
type : torch.FloatTensor
total number of eles in input tensor : 2
Stride is the jump necessary to go from one element to the next one in the specified dimension dim : (1,)


In [43]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,19]])
matrix

tensor([[ 7,  8],
        [ 9, 19]])

In [44]:
matrix.ndim

2

In [45]:
matrix[0]

tensor([7, 8])

In [46]:
matrix[1]

tensor([ 9, 19])

In [47]:
matrix.shape

torch.Size([2, 2])

In [48]:
print(f'dim : {matrix.ndim}')
print(f'size : {matrix.size()}')
print(f'type : {matrix.type()}')
print(f'total number of eles in input tensor : {matrix.numel()}')
print(f'Stride is the jump necessary to go from one element to the next one in the specified dimension dim : {matrix.stride()}')

dim : 2
size : torch.Size([2, 2])
type : torch.LongTensor
total number of eles in input tensor : 4
Stride is the jump necessary to go from one element to the next one in the specified dimension dim : (2, 1)


In [49]:
#higher dim
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [50]:
tensor.ndim

3

In [51]:
tensor.shape

torch.Size([1, 3, 3])

In [52]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
tensor[0][0]

tensor([1, 2, 3])

### Random tensors
why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers -> look at data -> update random number`

In [54]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9533, 0.8484, 0.8036, 0.2013],
        [0.7966, 0.2169, 0.0388, 0.5131],
        [0.3224, 0.3339, 0.9082, 0.9581]])

In [55]:
random_tensor.ndim

2

In [56]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224,224)) # height 224 pixels , width  224 pixels, color channels(R,G,B) 3 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [57]:
random_image_size_tensor

tensor([[[0.5111, 0.4410, 0.1655,  ..., 0.2208, 0.5917, 0.9691],
         [0.0382, 0.6094, 0.2126,  ..., 0.5203, 0.6424, 0.2446],
         [0.9359, 0.9619, 0.6652,  ..., 0.9698, 0.1653, 0.9623],
         ...,
         [0.8946, 0.0052, 0.5723,  ..., 0.6621, 0.7945, 0.9199],
         [0.2935, 0.0506, 0.8526,  ..., 0.3750, 0.9452, 0.5628],
         [0.4068, 0.5247, 0.7896,  ..., 0.3570, 0.9413, 0.7477]],

        [[0.7356, 0.9337, 0.4776,  ..., 0.4486, 0.3093, 0.7230],
         [0.7144, 0.4888, 0.1004,  ..., 0.1989, 0.4290, 0.5646],
         [0.3550, 0.0435, 0.3638,  ..., 0.0496, 0.6608, 0.3202],
         ...,
         [0.4189, 0.5876, 0.7562,  ..., 0.0741, 0.1753, 0.2402],
         [0.7085, 0.2837, 0.7055,  ..., 0.2579, 0.4221, 0.7077],
         [0.6174, 0.4193, 0.3247,  ..., 0.6319, 0.7100, 0.0727]],

        [[0.4888, 0.1382, 0.8165,  ..., 0.2518, 0.9401, 0.6966],
         [0.7530, 0.3554, 0.0931,  ..., 0.2534, 0.0119, 0.8242],
         [0.9689, 0.5065, 0.9673,  ..., 0.5563, 0.8858, 0.

In [58]:
torch.rand(size=(3,3))

tensor([[0.7323, 0.3344, 0.4196],
        [0.3945, 0.3507, 0.9051],
        [0.5545, 0.2258, 0.0123]])

### Zeros and ones

In [59]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [62]:
ones + random_tensor

tensor([[1.9533, 1.8484, 1.8036, 1.2013],
        [1.7966, 1.2169, 1.0388, 1.5131],
        [1.3224, 1.3339, 1.9082, 1.9581]])

In [63]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [64]:
# use torch.range() and get deprecated message, use torch.arange()
torch.arange(0,10)
ten = torch.arange(1,11)

In [65]:
one2ten = torch.arange(start=0,end=1000,step=8)
one2ten

tensor([  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96, 104,
        112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216,
        224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328,
        336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440,
        448, 456, 464, 472, 480, 488, 496, 504, 512, 520, 528, 536, 544, 552,
        560, 568, 576, 584, 592, 600, 608, 616, 624, 632, 640, 648, 656, 664,
        672, 680, 688, 696, 704, 712, 720, 728, 736, 744, 752, 760, 768, 776,
        784, 792, 800, 808, 816, 824, 832, 840, 848, 856, 864, 872, 880, 888,
        896, 904, 912, 920, 928, 936, 944, 952, 960, 968, 976, 984, 992])

In [66]:
# create tensors like
ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
ten_zeros = torch.zeros_like(input = ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
a = torch.zeros_like(input = one2ten)
a

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])

### Tensor datatypes

In [69]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device = None)
float_32_tensor

tensor([3., 6., 9.])

In [70]:
float_32_tensor.dtype

torch.float32

In [71]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= None, # what datatype is the tensor (e.g float32 or float16)
                               #computing number 32 bits / 16 bits to reflect precision
                               #sigal precision : 32 bits , half precision : 16 bits
                               device = None, # default = "cpu" could change it to "cuda"
                               # what device is your tensor on
                               requires_grad=False # whether or not to track gradients with this tensor operation
                               #with requires_grad set to True, which means that PyTorch will track any operations that involve x.
                               )
float_32_tensor

tensor([3., 6., 9.])

<b>Note</b> Tensor datatypes is one of 3 big errors you'll run into with PyTorch & deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

In [72]:
float_32_tensor.dtype

torch.float32

In [73]:
float_16_tensor = float_32_tensor.type(torch.float16) #convert float32 to float16 to deal with not match datatype
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [74]:
a = float_16_tensor * float_32_tensor  # it works , but some operation may not work
a

tensor([ 9., 36., 81.])

In [75]:
print(a.dtype)

torch.float32


In [76]:
int_32_tensor = torch.tensor([3,4,5],
                             dtype = torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [77]:
float_32_tensor * int_32_tensor

tensor([ 9., 24., 45.])

In [78]:
long = torch.tensor([3,4,5],
                             dtype = torch.long)
long

tensor([3, 4, 5])

In [79]:
float_32_tensor * long

tensor([ 9., 24., 45.])

### Getting information from tensors (tensors attribute)
1. Tensors not right datatype - to get datatype from a tensor , use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, use `tensor.device`

In [80]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3966, 0.2593, 0.6836, 0.2766],
        [0.0247, 0.2254, 0.0419, 0.6659],
        [0.3516, 0.3577, 0.7620, 0.4176]])

In [81]:
some_tensor.size , some_tensor.shape
# function         # attribute 

(<function Tensor.size>, torch.Size([3, 4]))

In [82]:
print(some_tensor)
print(f'data type of tensor:{some_tensor.dtype}') # default is float32
print(f'shape of tensor: {some_tensor.shape}')
print(f'device tensor is on: {some_tensor.device}')

tensor([[0.3966, 0.2593, 0.6836, 0.2766],
        [0.0247, 0.2254, 0.0419, 0.6659],
        [0.3516, 0.3577, 0.7620, 0.4176]])
data type of tensor:torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [83]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [84]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [85]:
# subtract 10 
tensor - 10

tensor([-9, -8, -7])

In [86]:
# try out Pytorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [87]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [88]:
torch.subtract(tensor,10)

tensor([-9, -8, -7])

### Matrix multiplication 
Two main ways of performing multiplication in neural network and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More info : https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisify:
1. The **inner dimensions** must match
* `(3,2) @ (3,2) ` won't work
* `(3,2) @ (2,3) ` will work
* `(2,3) @ (3,2) ` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2) ` -> `(2,2)`
* `(3,2) @ (2,3) ` -> `(3,3)`

In [89]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4578, 0.0564, 0.4206],
        [0.3460, 0.0636, 0.3237],
        [0.7087, 0.3797, 0.7324]])

In [90]:
# Element wise multiplication 
print(tensor, "*" , tensor)
print(f'equals {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals tensor([1, 4, 9])


In [91]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [92]:
tensor @ tensor

tensor(14)

In [93]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [94]:
%%time 
torch.matmul(tensor,tensor)


CPU times: user 182 µs, sys: 0 ns, total: 182 µs
Wall time: 155 µs


tensor(14)

In [95]:
%%time
value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 677 µs, sys: 0 ns, total: 677 µs
Wall time: 467 µs


tensor(14)

### One of the most common error in deep learning is `shape error`

In [96]:
# shape for matrix multiplication
a = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
b = torch.tensor([[7,8],
                  [9,10],
                  [11,12]])
torch.mm(a,b) # = torch.matmul(a,b)(it's an alias for matmul)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
a.shape , b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
b.T, b.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
b, b.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplication operations works when b is transposed
print(f'original shapes: a = {a.shape}, b={b.shape}')
print(f'new shapes: a = {a.shape} , b.T = {b.T.shape}')
print(f'multiplying:{a.shape} @ {b.T.shape} <- inner dimension must match')
print('output:\n')
print(f'output shape : {torch.mm(a,b.T).shape}')
torch.mm(a,b.T), torch.mm(a,b.T).shape 

original shapes: a = torch.Size([3, 2]), b=torch.Size([3, 2])
new shapes: a = torch.Size([3, 2]) , b.T = torch.Size([2, 3])
multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
output:

output shape : torch.Size([3, 3])


(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 torch.Size([3, 3]))

### Finding the min, max, mean, sum (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x)
# error : not the right data type
#mean cannot work on date type of LongTensor

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#change the dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#note : the torch.mean() function requires a tensor of float32/16 datatype to work

(tensor(45.), tensor(45.))

In [ ]:
#sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the index in tensor that has minimum value with argmin
x.argmin() 

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# find the index that has max value in tensor
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

### Reshape, stacking, squeezing and unsqueezing tensors

* Reshape - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the origial tensor
* Stacking - combine multiple tensors on the top of each other (vstack) or side by side (hstack)
* squeeze -remove all `1` dimension from a tensor
* unsqueeze - add a `1` dimension to a target tensor 
* permute - return a view of input with dimension permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1,7)
x_reshape


RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [ ]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.size()


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.size()


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
y = torch.arange(1.,11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
y.reshape(5,2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# change the view 
z = x.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view 
z = y.view(2,5)
z, z.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# changein z changes x(because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,y

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [ ]:
# stack tensors on the top of each otehr 
y_stacked = torch.stack([y,y,y,y], dim=0) # stack rows together
y_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [ ]:
# stack tensors on the top of each otehr 
y_stacked = torch.stack([y,y,y,y], dim=1) # stack vertically 
y_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# squeeze - remove all single dimensions from a target tensor
x_reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_reshape.shape

torch.Size([9, 1])

In [ ]:
x_reshape.squeeze(), x_reshape.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
print(f'previous tensor : {x_reshape}')
print(f'previous shape : {x_reshape.shape}')
print(f'squeeze tensor: {x_reshape.squeeze()}')
print(f'squeeze shape : {x_reshape.squeeze().shape}')

previous tensor : tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
previous shape : torch.Size([9, 1])
squeeze tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
squeeze shape : torch.Size([9])


In [ ]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim
print(f'pre target: {x_reshape.squeeze()}')
print(f'pre shape : {x_reshape.squeeze().shape}')

# add extra dim with unsqueeze
print(f'pre target: {x_reshape.squeeze().unsqueeze(dim=1)}')
print(f'pre shape : {x_reshape.squeeze().unsqueeze(dim=1).shape}')


pre target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
pre shape : torch.Size([9])
pre target: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
pre shape : torch.Size([9, 1])


In [ ]:
# torch.permute - rearrange dimension in a specific order
x = torch.rand(size=(224,224,3)) # height, width, color channels

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x.permute(2, 0, 1) # change order to "color , height , width"
print(f'prev shape:{x.shape}')
print(f'new shape:{x_permuted.shape}') #3,224,224

prev shape:torch.Size([224, 224, 3])
new shape:torch.Size([3, 224, 224])


### Indexing (select data from tensors)

Index with pytorch is similar to index with numpy

In [ ]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index on our new tensor
x[0], x[0].shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
x[0][0], x[0][0].shape

(tensor([1, 2, 3]), torch.Size([3]))

In [ ]:
x[0][0][0], x[0][0][0].shape

(tensor(1), torch.Size([]))

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
#we can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all the values of 0th and 1st dimensions but only index 1 and 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all the values of 0th but 1st index of 1 and 2 dim
x[:,1,1]

tensor([5])

In [ ]:
x[0,1,1]

tensor(5)

In [ ]:
# get index 0 of 0 th and 1st dim and all value of 2nd dimension
x[0,0,:] # = x[0][0]

tensor([1, 2, 3])

In [ ]:
#index on x to return 9 
x[0,2,2]

tensor(9)

In [ ]:
#index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

### PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing library.
And because of this Pytorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> numpy -> `torch.Tensor.numpy()`

In [ ]:
#numpy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# torch.from_numpy() function. This function creates a PyTorch tensor that shares the same memory block as the NumPy array, and any changes made to the tensor will be reflected in the original array.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype # warning : when converting from numpy -> pytorch convert it into float64 != float32

torch.float32

In [ ]:
#change the value of array, what will this do to `tensor`?
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
#Similarly, it is possible to create a NumPy array that shares the memory of a PyTorch tensor by using the numpy() method on the tensor.
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor, what happens to `numpy_tensor`
tensor += 1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

### Reproducability (trying to take random out of random)
In short how a neural network learns: 
`start with random numbers -> tensor operation -> update random numbers to try a better representation -> again`

To reduce the randomness in nn and pytorch comes the concept of **random seed**

Essentially what the random seed does is "flavor" the randomness.

In [ ]:
torch.rand(3, 3)

tensor([[0.4128, 0.0528, 0.1939],
        [0.7138, 0.2855, 0.0079],
        [0.9983, 0.1130, 0.6950]])

In [ ]:
a = torch.rand(3,4)
b = torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.4544, 0.4206, 0.0220, 0.5979],
        [0.6711, 0.2130, 0.7970, 0.9867],
        [0.6485, 0.4439, 0.0992, 0.5385]])
tensor([[0.1938, 0.2763, 0.0535, 0.7973],
        [0.8626, 0.6485, 0.6655, 0.0068],
        [0.9302, 0.3894, 0.3191, 0.6616]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensors
random_seed = 42
torch.manual_seed(random_seed)
c = torch.rand(3,4)
torch.manual_seed(random_seed) # need to reset the random seed before rand execute 
d = torch.rand(3,4)
print(c)
print(d)
print(c==d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


More resource : https://pytorch.org/docs/stable/notes/randomness.html

### running tensors and pytorch objects on the GPUs ( and make faster computations)
GPUs = faster computations on numbers ,thanks to CUDA + NVIDIA hardware + Pytorch 

### getting a GPU 
1. Easiest 

In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Mon Feb 20 20:12:36 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:19:00.0 Off |                  N/A |
| 23%   42C    P5    14W / 250W |      2MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 29%   

### check for GPU access with pytorch 

In [ ]:
torch.cuda.is_available()

True

For pytorch since it's capable of running compute on the GPU or CPU, it's best practie to setup device agnostic code

In [ ]:
#setup device agnostic code 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device


'cuda'

In [ ]:
#count number of devices 
torch.cuda.device_count()
#we have four cuda

4

## 3.putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU cuz it's have faster computation

In [2]:
import torch
t = torch.tensor([1,2,3])

print(t, t.device)

tensor([1, 2, 3]) cpu


In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# move tensor to gpu if available 
t_on_gpu = t.to(device)
t_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Move tensors back to CPU 
(since numpy compute on CPU)

In [4]:
# if tensor is on GPU, can't transform it to numpy
t_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
#to fix the gpu tensor with numpy issue, we can first set it to cpu
t_backon_cpu = t_on_gpu.cpu().numpy()
t_backon_cpu

array([1, 2, 3])

In [10]:
t_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercise 